# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Raúl Ávila
tagline:          Blog
url:              http://raulavila.github.io
paginate:         5
baseurl:          http://raulavila.github.io/
author:
  name:           Raul Avila
  url:            https://twitter.com/ravila80
  email:          ravila80@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/raulavila/raulavila.github.io
